-- Les données sont initialisées par DataInitializer.java au démarrage.
-- Mot de passe de tous les comptes de démo : "password"
--   Médecins : doc.john / doc.paul
--   Patients : pat.marc / pat.jean
